### ISSUE TITLE
Script to make artifact available

### ISSUE THREAD

**Issue by mateusrovedaa** [aztecweb/repman#5]
Create a script to make package artifacts available based on a repository.

The process to be followed will be:
- Zips of packages are sent to repository
- Pull from repository
- Script for inserting composer.json into the plugin package and making the artifact available
- Ignores if the package already exists in the artifact directory
- Adds composer.json with the package type, plugin name and version:
  - Package type: wordpress-plugin or wordpress-theme
  - Package name: aztecweb-[plugin or theme]/[package slug taken from file name]
  - Version: taken from filename
- Store package to artifact directory
- Synchronize package using bin/console repman:package:synchronize

#### Repository structure

- plugin
  - wp-rocket
    - wp-rocket.3.14.4.1.zip
    - wp-rocket.3.14.4.2.zip
    - wp-rocket.3.15.zip
...

- theme
  - oceanwp
    - oceanwp-3.4.6.zip
    - oceanwp-3.4.7.zip
    - oceanwp-3.5.0.zip
...

#### Artifact structure

- oceanwp
  - oceanwp-3.4.6.zip
  - oceanwp-3.4.7.zip
  - oceanwp-3.5.0.zip

- wp-rocket
  - wp-rocket.3.14.4.1.zip
  - wp-rocket.3.14.4.2.zip
  - wp-rocket.3.15.zip

**Comment by mateusrovedaa** [comment]
To run the script is necessary to setting up a env variable in `.env.local` file to define the artifacts path.

```
ARTIFACTS_REPOSITORY_PATH=/opt/repman-artifacts
```

## How to use the script

You need to pass the package name and the type.

```bash
$ sudo /opt/repman/current/resources/scripts/create-composer-package.sh wp-rocket-3.16.zip plugin
```
If you don't pass the package name and type, the script was run to all .zip in `ARTIFACTS_REPOSITORY_PATH`.

#### Before script run

![image](https://github.com/aztecweb/repman/assets/22747307/0bb9e593-dc3f-48cf-a94b-54f903711322)

#### After script run

```bash
$ sudo /opt/repman/current/resources/scripts/create-composer-package.sh wp-rocket-3.15.5.zip plugin
```

![image](https://github.com/aztecweb/repman/assets/22747307/e4543454-0982-4408-bfd9-a98a9769de2d)

## Evidences

```bash
ls -lha /opt/repman/current/var/repo/
total 16K
drwxr-xr-x 4 repman repman 4.0K Jul  2 17:15 .
drwxr-xr-x 7 repman repman 4.0K Jun 21 17:58 ..
drwxr-xr-x 4 repman repman 4.0K Jul  2 17:15 aztec
drwxr-xr-x 2 repman repman 4.0K Jul  2 17:36 wp-rocket
```

```bash
$ ls -lha /opt/repman/current/var/repo/wp-rocket/
total 7.2M
drwxr-xr-x 2 repman repman 4.0K Jul  2 17:36 .
drwxr-xr-x 4 repman repman 4.0K Jul  2 17:15 ..
-rw-r--r-- 1 repman repman 3.5M Jul  2 17:36 wp-rocket-3.15.5.zip
-rw-r--r-- 1 repman repman 3.7M Jul  2 17:14 wp-rocket-3.16.zip
```

The Aztec folder is created when we use the sync command. The name is the same as the organization.
```
bash
$ ls -lha /opt/repman/current/var/repo/aztec/
total 16K
drwxr-xr-x 4 repman repman 4.0K Jul  2 17:15 .
drwxr-xr-x 4 repman repman 4.0K Jul  2 17:15 ..
drwxr-xr-x 3 repman repman 4.0K Jul  2 17:15 dist
drwxr-xr-x 3 repman repman 4.0K Jul  2 17:15 p
```

Test  installing a package

![image](https://github.com/aztecweb/repman/assets/22747307/1d183f22-0e2f-446e-8a0b-75f2ca3f667c)

**Comment by edpittol** [comment]
I added the `ARTIFACTS_REPOSITORY_PATH` variable on the `.env` files that I think make senses (https://github.com/aztecweb/repman/pull/6/commits/87db6b2488e3a9dfc49080220616ed05c43249ca).

**Comment by edpittol** [comment]
The script must validate if the package is already on Repman.

**Comment by mateusrovedaa** [comment]
I'm my tests, I uploaded a new file and I executed the script again. In this execution I discovered that we first need to create the folder to store the packages, run the script and then add it to the interface.

``` bash
$ sudo mkdir /opt/repman/shared/var/repo/wp-all-import-pro
$ sudo chown repman:repman /opt/repman/shared/var/repo/wp-all-import-pro
$ sudo /opt/repman/current/resources/scripts/create-composer-package.sh wp-all-import-pro-4.8.7.zip plugin
```

At the last, we need to create the package on interface.

![image](https://github.com/user-attachments/assets/8eaad217-ade9-4c51-818b-01b5f0c2f643)

![image](https://github.com/user-attachments/assets/f8809a09-094c-46c2-95b0-a8fae8d7c348)

Because of that, I create a new step into the script to create the folder if does not exists and output a message to create the package in Repman.

```bash
if ! package_exists; then
   echo "${PACKAGE_NAME} package folder does not exists. Creating the folder... You need to create the package in Repman too."
   mkdir "${package_destination}"
   chown repman:repman "${package_destination}"
fi
```

I tested again with a non-exists package:

**Before**
```
$ ls -lha /opt/repman/current/var/repo/
total 20K
drwxr-xr-x 5 repman repman 4.0K Jul 19 14:59 .
drwxr-xr-x 7 repman repman 4.0K Jun 21 17:58 ..
drwxr-xr-x 4 repman repman 4.0K Jul  2 17:15 aztec
drwxr-xr-x 2 repman repman 4.0K Jul 19 14:59 wp-all-import-pro
drwxr-xr-x 2 repman repman 4.0K Jul  2 20:08 wp-rocket
```

**After**
```bash
$ sudo /opt/repman/current/resources/scripts/create-composer-package.sh ithemes-security-pro-8.5.0.zip plugin
...
+ [[ -d /opt/repman/releases/3112f9588bb37a58b0020692a36d6e3838d67047/var/repo/ithemes-security-pro ]]
+ echo -e '\033[31mithemes-security-pro package folder does not exists. Creating the folder... You need to create the package in Repman too.\033[0m'
ithemes-security-pro package folder does not exists. Creating the folder... You need to create the package in Repman too.

$ ls -lha /opt/repman/current/var/repo/
$ ls -lha /opt/repman/current/var/repo/
total 24K
drwxr-xr-x 6 repman repman 4.0K Jul 22 13:53 .
drwxr-xr-x 7 repman repman 4.0K Jun 21 17:58 ..
drwxr-xr-x 4 repman repman 4.0K Jul  2 17:15 aztec
drwxr-xr-x 2 repman repman 4.0K Jul 22 13:53 ithemes-security-pro
drwxr-xr-x 2 repman repman 4.0K Jul 19 14:59 wp-all-import-pro
drwxr-xr-x 2 repman repman 4.0K Jul  2 20:08 wp-rocket
```
The message is displayed in red to attract attention.

![image](https://github.com/user-attachments/assets/9c55a4e2-de73-4d8e-95df-8f3593f045aa)

After that, I created the package in Repman UI.

![image](https://github.com/user-attachments/assets/46bebf74-7772-4d66-a00f-acc3595c5f0f)

![image](https://github.com/user-attachments/assets/4265c386-ae2d-4d13-a27a-2f3e9f480a47)


I also created a new function to check if the script is running with sudo user.

**Comment by mateusrovedaa** [comment]
Removed the issue script. We versioned it in another repository so as not to confuse it with repman files.
